# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)


#El ideal abria sido utilizar iteraciones para la creacion del seed, pero en esta ocasion
#y dado a la naturaleza de mi aplicacion y el tiempo, decidi hacerlos manualmente.

# Creacion de usuarios
User.create( email: "admin@gmail.com", password: "123456", password_confirmation: "123456", role: 1)
User.create( email: "operador1@gmail.com", password: "123456", password_confirmation: "123456")
User.create( email: "operador2@gmail.com", password: "123456", password_confirmation: "123456")
User.create( email: "operador3@gmail.com", password: "123456", password_confirmation: "123456")
User.create( email: "operador4@gmail.com", password: "123456", password_confirmation: "123456")
User.create( email: "operador5@gmail.com", password: "123456", password_confirmation: "123456")
# Creacion de Features/tipo de equipo
Feature.create( name: "Motor a reacción")
Feature.create( name: "Motor turbohélice")
# Creacion de Upkeeptipe/tipo de mantenimiento
Upkeeptipe.create( name: "Preventivo")
Upkeeptipe.create( name: "Correctivo")
# Creacion de Material/materiales usados
Material.create( name:"Turbinas")
Material.create( name:"Sistemas de ignicion")
Material.create( name:"Sistemas de combustible")
# Creacion de City/ciudades
City.create( name:"Arica")
City.create( name:"Iquique")
City.create( name:"Antofagasta")
City.create( name:"La serena")
City.create( name:"Coquimbo")
City.create( name:"Santiago")
City.create( name:"Talca")
City.create( name:"Concepcion")
City.create( name:"Temuco")
City.create( name:"Punta Arenas")
# Creacion de Engine/Motores
Engine.create( name:"REAC-1", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"TURBO-1", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-2", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-2", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-3", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-3", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-4", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-4", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-5", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-5", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-6", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-6", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-7", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-7", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-8", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-8", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-9", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-9", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
Engine.create( name:"REAC-10", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:2)
Engine.create( name:"TURBO-10", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit", feature_id:1)
# Creacion de Upkeep/Mantenimiento
Upkeep.create( date:"03-01-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:1, engine_id:1, material_ids: [1,2,3])
Upkeep.create( date:"04-01-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:2, engine_id:2, material_ids: [1])
Upkeep.create( date:"05-01-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:1, engine_id:3, material_ids: [3])
Upkeep.create( date:"06-01-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:4, material_ids: [2,3])
Upkeep.create( date:"07-01-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:2, engine_id:5, material_ids: [1,2])
Upkeep.create( date:"08-01-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:1, engine_id:6, material_ids: [1,2,3])
Upkeep.create( date:"09-01-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:2, engine_id:7, material_ids: [1,3])
Upkeep.create( date:"10-01-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:1, engine_id:8, material_ids: [1,2,3])
Upkeep.create( date:"11-01-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:2, engine_id:9, material_ids: [1,3])
Upkeep.create( date:"12-01-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:1, engine_id:10, material_ids: [1,3])
Upkeep.create( date:"13-01-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:2, engine_id:11, material_ids: [1,2,3])
Upkeep.create( date:"14-01-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:1, engine_id:12, material_ids: [1,3])
Upkeep.create( date:"15-01-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:2, engine_id:13, material_ids: [1,2])
Upkeep.create( date:"16-01-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:14, material_ids: [1,2,3])
Upkeep.create( date:"17-01-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:2, engine_id:15, material_ids: [2,3])
Upkeep.create( date:"18-01-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:1, engine_id:16, material_ids: [1,2])
Upkeep.create( date:"19-01-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:2, engine_id:17, material_ids: [1,2,3])
Upkeep.create( date:"20-01-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:1, engine_id:18, material_ids: [1,3])
Upkeep.create( date:"21-01-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:2, engine_id:19, material_ids: [1,3])
Upkeep.create( date:"22-01-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:1, engine_id:20, material_ids: [1,2,3])
Upkeep.create( date:"23-01-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:2, engine_id:1, material_ids: [3])
Upkeep.create( date:"24-01-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:1, engine_id:2, material_ids: [1,3])
Upkeep.create( date:"25-01-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:2, engine_id:3, material_ids: [1,2,3])
Upkeep.create( date:"26-01-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:4, material_ids: [3])
Upkeep.create( date:"27-01-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:2, engine_id:5, material_ids: [1,2])
Upkeep.create( date:"28-01-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:1, engine_id:6, material_ids: [1,2,3])
Upkeep.create( date:"29-01-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:2, engine_id:7, material_ids: [2,3])
Upkeep.create( date:"30-01-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:2, engine_id:8, material_ids: [1,2,3])
Upkeep.create( date:"01-02-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:1, engine_id:9, material_ids: [1,3])
Upkeep.create( date:"02-02-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:2, engine_id:10, material_ids: [1,3])
Upkeep.create( date:"03-02-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:1, engine_id:11, material_ids: [1,2,3])
Upkeep.create( date:"04-02-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:2, engine_id:12, material_ids: [1,3])
Upkeep.create( date:"05-02-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:1, engine_id:13, material_ids: [1,3])
Upkeep.create( date:"06-02-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:2, engine_id:14, material_ids: [1,2,3])
Upkeep.create( date:"07-02-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:2, engine_id:15, material_ids: [1,3])
Upkeep.create( date:"08-02-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:2, engine_id:16, material_ids: [1,3])
Upkeep.create( date:"09-02-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:1, engine_id:17, material_ids: [1,2,3])
Upkeep.create( date:"10-02-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:2, engine_id:18, material_ids: [1,3])
Upkeep.create( date:"11-02-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:1, engine_id:19, material_ids: [1,2,3])
Upkeep.create( date:"12-02-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:2, engine_id:20, material_ids: [1,3])
Upkeep.create( date:"13-02-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:2, engine_id:1, material_ids: [2,3])
Upkeep.create( date:"14-02-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:1, engine_id:2, material_ids: [1,2,3])
Upkeep.create( date:"15-02-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:2, engine_id:3, material_ids: [1,3])
Upkeep.create( date:"16-02-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:4, material_ids: [1,2,3])
Upkeep.create( date:"17-02-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:2, engine_id:5, material_ids: [1,3])
Upkeep.create( date:"18-02-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:1, engine_id:6, material_ids: [1,2,3])
Upkeep.create( date:"19-02-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:2, engine_id:7, material_ids: [1,3])
Upkeep.create( date:"20-02-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:1, engine_id:8, material_ids: [1,3])
Upkeep.create( date:"21-02-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:2, engine_id:9, material_ids: [1,2,3])
Upkeep.create( date:"22-02-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:2, engine_id:10, material_ids: [1,3])
Upkeep.create( date:"23-02-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:2, engine_id:11, material_ids: [2,3])
Upkeep.create( date:"25-02-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:1, engine_id:12, material_ids: [1,2,3])
Upkeep.create( date:"26-02-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:2, engine_id:13, material_ids: [1,3])
Upkeep.create( date:"27-02-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:14, material_ids: [1,3])
Upkeep.create( date:"28-02-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:1, engine_id:15, material_ids: [1,2,3])
Upkeep.create( date:"01-03-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:1, engine_id:16, material_ids: [1,3])
Upkeep.create( date:"02-03-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:1, engine_id:17, material_ids: [1,3])
Upkeep.create( date:"03-03-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:1, engine_id:18, material_ids: [1,2,3])
Upkeep.create( date:"04-03-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:2, engine_id:19, material_ids: [1,3])
Upkeep.create( date:"05-03-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:2, engine_id:20, material_ids: [1,3])
Upkeep.create( date:"06-03-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:2, engine_id:1, material_ids: [1,3])
Upkeep.create( date:"07-03-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:2, engine_id:2, material_ids: [1,3])
Upkeep.create( date:"08-03-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:2, engine_id:3, material_ids: [1,2,3])
Upkeep.create( date:"09-03-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:4, material_ids: [2,3])
Upkeep.create( date:"10-03-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:1, engine_id:5, material_ids: [1,3])
Upkeep.create( date:"11-03-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:1, engine_id:6, material_ids: [1,2,3])
Upkeep.create( date:"12-03-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:1, engine_id:7, material_ids: [1,3])
Upkeep.create( date:"13-03-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:2, engine_id:8, material_ids: [1,2,3])
Upkeep.create( date:"14-03-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:2, engine_id:9, material_ids: [1,3])
Upkeep.create( date:"15-03-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:2, engine_id:10, material_ids: [1,3])
Upkeep.create( date:"16-03-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:1, engine_id:11, material_ids: [1,2,3])
Upkeep.create( date:"17-03-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:2, engine_id:12, material_ids: [1,3])
Upkeep.create( date:"18-03-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:1, engine_id:13, material_ids: [1,3])
Upkeep.create( date:"19-03-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:14, material_ids: [2,3])
Upkeep.create( date:"20-03-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:1, engine_id:15, material_ids: [1,3])
Upkeep.create( date:"21-03-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:1, engine_id:16, material_ids: [1,2,3])
Upkeep.create( date:"22-03-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:2, engine_id:17, material_ids: [1,3])
Upkeep.create( date:"23-03-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:2, engine_id:18, material_ids: [1,3])
Upkeep.create( date:"24-03-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:1, engine_id:19, material_ids: [1,2,3])
Upkeep.create( date:"25-03-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:1, engine_id:20, material_ids: [1,3])
Upkeep.create( date:"26-03-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:1, engine_id:1, material_ids: [1,3])
Upkeep.create( date:"27-03-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:1, engine_id:2, material_ids: [1,3])
Upkeep.create( date:"28-03-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:1, engine_id:3, material_ids: [1,2,3])
Upkeep.create( date:"29-03-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:4, material_ids: [1,2])
Upkeep.create( date:"30-03-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:2, engine_id:5, material_ids: [1,3])
Upkeep.create( date:"01-04-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:2, engine_id:6, material_ids: [1,2,3])
Upkeep.create( date:"02-04-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:2, engine_id:7, material_ids: [1])
Upkeep.create( date:"03-04-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:1, engine_id:8, material_ids: [1,2])
Upkeep.create( date:"04-04-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:1, engine_id:9, material_ids: [1,3])
Upkeep.create( date:"05-04-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:2, engine_id:10, material_ids: [3])
Upkeep.create( date:"06-04-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:1, engine_id:11, material_ids: [1,2,3])
Upkeep.create( date:"07-04-2022", email:"operador2@gmail.com", city_id:2, upkeeptipe_id:1, engine_id:12, material_ids: [2,3])
Upkeep.create( date:"08-04-2022", email:"operador3@gmail.com", city_id:3, upkeeptipe_id:2, engine_id:13, material_ids: [1,2,3])
Upkeep.create( date:"09-04-2022", email:"operador4@gmail.com", city_id:4, upkeeptipe_id:1, engine_id:14, material_ids: [3])
Upkeep.create( date:"10-04-2022", email:"operador5@gmail.com", city_id:5, upkeeptipe_id:1, engine_id:15, material_ids: [1,2,3])
Upkeep.create( date:"11-04-2022", email:"operador1@gmail.com", city_id:6, upkeeptipe_id:1, engine_id:16, material_ids: [2,3])
Upkeep.create( date:"12-04-2022", email:"operador2@gmail.com", city_id:7, upkeeptipe_id:2, engine_id:17, material_ids: [1,2,3])
Upkeep.create( date:"13-04-2022", email:"operador3@gmail.com", city_id:8, upkeeptipe_id:1, engine_id:18, material_ids: [1])
Upkeep.create( date:"14-04-2022", email:"operador4@gmail.com", city_id:9, upkeeptipe_id:2, engine_id:19, material_ids: [1,2,3])
Upkeep.create( date:"15-04-2022", email:"operador5@gmail.com", city_id:10, upkeeptipe_id:1, engine_id:20, material_ids: [1,3])
Upkeep.create( date:"16-04-2022", email:"operador1@gmail.com", city_id:1, upkeeptipe_id:2, engine_id:1, material_ids: [1,2])